### ISSUE TITLE
Unable to loop items

### ISSUE THREAD

**Issue by dchandrika** [sheikalthaf/ResCarousel#2]
I want to have looping effect on items, means I have 10 items in list, once 10th item reaches instead of hiding right arrow I want to see 1st item, same in left side aswell, after reaching 1st item, instead of hiding left arrow, want to see 10th item on click on left arrow. Will that be possible?

**Comment by sheikalthaf** [comment]
Sorry for the late reply. It is not possible to loop item but I make you to go to first item. I already working on a update and I will update it soon

**Comment by sheikalthaf** [comment]
added the looping of the items in current release and also the speed control
